<a href="https://colab.research.google.com/github/Nekoiii/ML_Practices_colab/blob/main/pytorch_basic_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [7]:
# Creates tensor variable
x = torch.tensor([3.0])
print(x,x.dtype)

x = torch.tensor([8] )
print(x,x.dtype)

x = torch.tensor([8] , dtype = torch.float)
print(x,x.dtype)

tensor([3.]) torch.float32
tensor([8]) torch.int64
tensor([8.]) torch.float32


In [ ]:
# numpy.ndarray and torch.tensor can be converted interchangeably.
import torch
import numpy as np

t = torch.tensor([[3.0, 2.0], [5.0, 6.0]])
t_to_arr = t.numpy()
print(t,t.dtype,'\n',t_to_arr,t_to_arr.dtype)

arr = np.array([[3.0,2.0],[5.0,6.0]])
arr_to_t = torch.from_numpy(arr)
print(arr,arr.dtype,'\n',arr_to_t,arr_to_t.dtype)

In [22]:
# Change data type
# (PyTorch defaults to float32, while NumPy defaults to float64)

x=torch.tensor([[3.0, 2.0], [5.0, 6.0]])
x_modified=x.to(torch.float32)
print(x.dtype,x_modified.dtype)

x=np.array([[3.0, 2.0], [5.0, 6.0]])
x_modified=x.astype(np.float64)
print(x.dtype,x_modified.dtype)

torch.float32 torch.float32
float64 float32
